apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
        - name: ping
          image: ping-service
          # never pull the image policy so we can use local docker image
          imagePullPolicy: Never
          env:
            - name: EXTERNAL_API
              valueFrom:
                configMapKeyRef:
                  name: external-api-configmap
                  key: url
            - name: SECRET_USER
              valueFrom:
                secretKeyRef:
                  name: external-api-secret
                  key: username
            - name: SECRET_PASS
              valueFrom:
                secretKeyRef:
                  name: external-api-secret
                  key: password              
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  selector:
    app: ping
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30000

